color: fuchsia
fieldLayouts:
  e68a4ed3-dce7-4e69-bd9f-0ed641ef318b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-20T18:50:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6ba554d2-7dfc-4b8a-b3ad-81dccbe6af2e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cadb26d2-3a30-4c88-acac-a4e20aee7db7
        userCondition: null
handle: typeOf_Therapy
hasTitleField: true
icon: null
name: 'Type of therapy'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
