<?php
/**
 * Site URL Rules
 *
 * You can define custom site URL rules here, which Craft will check in addition
 * to routes defined in Settings → Routes.
 *
 * Read all about Craft’s routing behavior, here:
 * https://craftcms.com/docs/4.x/routing.html
 */

return [
    // This route uses the special `{uid}` token, which will
    // match any UUIDv4 generated by Craft:
    'enquiry-submitted/<entryUid:{uid}>' => ['template' => 'enquiries/enquiry-submitted'],
    'contact-form-submitted/<entryUid:{uid}>' => ['template' => 'enquiries/contact-form-submitted'],
];
