altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  10bb0d2f-832e-448c-ada7-e3fadda2f726:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-29T14:09:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 22dba506-8346-4500-a838-7dd9485491bc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 954b8e47-bf10-4c42-9eaa-36797b270e88
        userCondition: null
fs: generalImages
handle: images
name: Images
sortOrder: 3
subpath: general
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: generalImages
transformSubpath: ''
