columnSuffix: null
handle: body
instructions: null
name: Body
searchable: false
settings:
  errorMessage: 'Unable to find component class ''craft\ckeditor\Field''.'
  expectedType: craft\ckeditor\Field
  settings:
    __assoc__:
      0:
        - availableTransforms
        - ''
      1:
        - availableVolumes
        - '*'
      5:
        - enableSourceEditingForNonAdmins
        - false
      6:
        - entryTypes
        -
          - aea81fe7-465e-41aa-9b2c-04e6578b3c4b # Article
      8:
        - purifyHtml
        - true
      9:
        - showUnpermittedFiles
        - false
      10:
        - showUnpermittedVolumes
        - false
      11:
        - showWordCount
        - false
translationKeyFormat: null
translationMethod: none
type: craft\fields\MissingField
