columnSuffix: null
handle: profileComplete
instructions: null
name: 'Profile complete'
searchable: false
settings:
  default: false
  offLabel: 'Not Live'
  onLabel: Live
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
