columnSuffix: null
handle: qualifications
instructions: 'Please write your formal qualifications here'
name: Qualifications
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
