defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: de726837-6d2f-494c-921c-8dfbd363fbf4 # Issues index
handle: issuesIndex
maxAuthors: 1
name: 'Issues index'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c0ed5fcd-bf5e-4d52-9094-794f737b4080: # Brighton Counselling Directory
    enabledByDefault: true
    hasUrls: true
    template: issues/index.twig
    uriFormat: issues-therapy-helps
type: single
