defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2a807641-d923-4a22-8412-0e6fe9cde8e6 # mainnav
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c0ed5fcd-bf5e-4d52-9094-794f737b4080: # Brighton Counselling Directory
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 0eb78fba-1977-4755-947b-2ab84874ed72
type: structure
